"""Create projects and files tables.

Revision ID: 20260328_0001
Revises:
Create Date: 2026-03-28 00:00:00

"""

from __future__ import annotations

import alembic.op as op


revision = '20260328_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.execute(
        """
        CREATE TABLE projects (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            git_url TEXT NOT NULL,
            summary TEXT,
            embedding vector,
            language TEXT,
            last_updated TIMESTAMPTZ,
            default_branch TEXT,
            CONSTRAINT uq_projects_git_url UNIQUE (git_url)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE files (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            path TEXT NOT NULL,
            summary TEXT,
            embedding vector,
            checksum TEXT NOT NULL,
            last_updated TIMESTAMPTZ,
            CONSTRAINT uq_files_project_path UNIQUE (project_id, path)
        )
        """
    )

    op.create_index('ix_files_project_id', 'files', ['project_id'])


def downgrade() -> None:
    op.drop_index('ix_files_project_id', table_name='files')
    op.execute('DROP TABLE files')
    op.execute('DROP TABLE projects')
